CCOPTS=--std=c++17 -Wall -O2

.DEFAULT_GOAL := all

.PHONY : all
all : problem1 problem2 problem3 problem4 problem5 problem6 problem7 problem8 problem9 problem10 problem11 problem12 problem13 problem14

